//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jojatekok.MoneroGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jojatekok.MoneroGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading license file....
        /// </summary>
        public static string AboutWindowLicenseFileLoading {
            get {
                return ResourceManager.GetString("AboutWindowLicenseFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The license file cannot be found..
        /// </summary>
        public static string AboutWindowLicenseFileNotFound {
            get {
                return ResourceManager.GetString("AboutWindowLicenseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party licenses.
        /// </summary>
        public static string AboutWindowThirdPartyLicenses {
            get {
                return ResourceManager.GetString("AboutWindowThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Monero Client.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DebugConsoleClear {
            get {
                return ResourceManager.GetString("DebugConsoleClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string DebugConsoleSend {
            get {
                return ResourceManager.GetString("DebugConsoleSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon.
        /// </summary>
        public static string DebugWindowConsoleDaemon {
            get {
                return ResourceManager.GetString("DebugWindowConsoleDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consoles.
        /// </summary>
        public static string DebugWindowConsoles {
            get {
                return ResourceManager.GetString("DebugWindowConsoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string DebugWindowConsoleWallet {
            get {
                return ResourceManager.GetString("DebugWindowConsoleWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DebugWindowInformation {
            get {
                return ResourceManager.GetString("DebugWindowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug window.
        /// </summary>
        public static string DebugWindowTitle {
            get {
                return ResourceManager.GetString("DebugWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        public static string MainWindowAddressBook {
            get {
                return ResourceManager.GetString("MainWindowAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monero Client is shutting down....
        /// </summary>
        public static string MainWindowBusyStatusShutdown {
            get {
                return ResourceManager.GetString("MainWindowBusyStatusShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MainWindowOverview {
            get {
                return ResourceManager.GetString("MainWindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send coins.
        /// </summary>
        public static string MainWindowSendCoins {
            get {
                return ResourceManager.GetString("MainWindowSendCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string MainWindowTransactions {
            get {
                return ResourceManager.GetString("MainWindowTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Monero Client.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Backup wallet....
        /// </summary>
        public static string MenuBackupWallet {
            get {
                return ResourceManager.GetString("MenuBackupWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change wallet passphrase....
        /// </summary>
        public static string MenuChangeWalletPassword {
            get {
                return ResourceManager.GetString("MenuChangeWalletPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Debug window.
        /// </summary>
        public static string MenuDebugWindow {
            get {
                return ResourceManager.GetString("MenuDebugWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Encrypt wallet....
        /// </summary>
        public static string MenuEncryptWallet {
            get {
                return ResourceManager.GetString("MenuEncryptWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unlock wallet....
        /// </summary>
        public static string MenuUnlockWallet {
            get {
                return ResourceManager.GetString("MenuUnlockWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string OverviewCopy {
            get {
                return ResourceManager.GetString("OverviewCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string OverviewInitializing {
            get {
                return ResourceManager.GetString("OverviewInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of transactions:.
        /// </summary>
        public static string OverviewNumberOfTransactions {
            get {
                return ResourceManager.GetString("OverviewNumberOfTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent transactions.
        /// </summary>
        public static string OverviewRecentTransactions {
            get {
                return ResourceManager.GetString("OverviewRecentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendable:.
        /// </summary>
        public static string OverviewSpendable {
            get {
                return ResourceManager.GetString("OverviewSpendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed:.
        /// </summary>
        public static string OverviewUnconfirmed {
            get {
                return ResourceManager.GetString("OverviewUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string OverviewWallet {
            get {
                return ResourceManager.GetString("OverviewWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Monero address.
        /// </summary>
        public static string SendCoinsAddressHint {
            get {
                return ResourceManager.GetString("SendCoinsAddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a label for this address to add it to your address book.
        /// </summary>
        public static string SendCoinsLabelHint {
            get {
                return ResourceManager.GetString("SendCoinsLabelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix count:.
        /// </summary>
        public static string SendCoinsMixCount {
            get {
                return ResourceManager.GetString("SendCoinsMixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment ID:.
        /// </summary>
        public static string SendCoinsPaymentId {
            get {
                return ResourceManager.GetString("SendCoinsPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is optional.
        /// </summary>
        public static string SendCoinsPaymentIdHint {
            get {
                return ResourceManager.GetString("SendCoinsPaymentIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendCoinsSend {
            get {
                return ResourceManager.GetString("SendCoinsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections.
        /// </summary>
        public static string StatusBarConnections {
            get {
                return ResourceManager.GetString("StatusBarConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with network....
        /// </summary>
        public static string StatusBarStatusSynchronizing {
            get {
                return ResourceManager.GetString("StatusBarStatusSynchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string StatusBarSyncTextDays {
            get {
                return ResourceManager.GetString("StatusBarSyncTextDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blocks ({1} {2}) behind.
        /// </summary>
        public static string StatusBarSyncTextMain {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TextAddress {
            get {
                return ResourceManager.GetString("TextAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TextAmount {
            get {
                return ResourceManager.GetString("TextAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monero Client.
        /// </summary>
        public static string TextClientName {
            get {
                return ResourceManager.GetString("TextClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMR.
        /// </summary>
        public static string TextCurrencyCode {
            get {
                return ResourceManager.GetString("TextCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string TextLabel {
            get {
                return ResourceManager.GetString("TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendable?.
        /// </summary>
        public static string TransactionsSpendable {
            get {
                return ResourceManager.GetString("TransactionsSpendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TransactionsType {
            get {
                return ResourceManager.GetString("TransactionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string TransactionTypeReceive {
            get {
                return ResourceManager.GetString("TransactionTypeReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TransactionTypeSend {
            get {
                return ResourceManager.GetString("TransactionTypeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string TransactionTypeUnknown {
            get {
                return ResourceManager.GetString("TransactionTypeUnknown", resourceCulture);
            }
        }
    }
}
