//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jojatekok.MoneroGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jojatekok.MoneroGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons made by:.
        /// </summary>
        public static string AboutWindowCreditIcons {
            get {
                return ResourceManager.GetString("AboutWindowCreditIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading license file....
        /// </summary>
        public static string AboutWindowLicenseFileLoading {
            get {
                return ResourceManager.GetString("AboutWindowLicenseFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The license file cannot be found..
        /// </summary>
        public static string AboutWindowLicenseFileNotFound {
            get {
                return ResourceManager.GetString("AboutWindowLicenseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party licenses.
        /// </summary>
        public static string AboutWindowThirdPartyLicenses {
            get {
                return ResourceManager.GetString("AboutWindowThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Monero Client.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address.
        /// </summary>
        public static string AddressBookCopyAddress {
            get {
                return ResourceManager.GetString("AddressBookCopyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add known address.
        /// </summary>
        public static string AddressBookEditWindowTitleAdd {
            get {
                return ResourceManager.GetString("AddressBookEditWindowTitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contact.
        /// </summary>
        public static string AddressBookEditWindowTitleEdit {
            get {
                return ResourceManager.GetString("AddressBookEditWindowTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a method for creating the new backup!.
        /// </summary>
        public static string BackupManagerNewBackupWindowInstructionMain {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowInstructionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a file, at a chosen path.
        /// </summary>
        public static string BackupManagerNewBackupWindowSelectionAsFileCustom1 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsFileCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files will not appear as selectable in the built-in backup manager.
        /// </summary>
        public static string BackupManagerNewBackupWindowSelectionAsFileCustom2 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsFileCustom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a file, at the default location.
        /// </summary>
        public static string BackupManagerNewBackupWindowSelectionAsFileDefault {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsFileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a deterministic wallet seed.
        /// </summary>
        public static string BackupManagerNewBackupWindowSelectionAsSeed1 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsSeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is the safest, and it doesn&apos;t even require a computer for storage.
        /// </summary>
        public static string BackupManagerNewBackupWindowSelectionAsSeed2 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsSeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New backup.
        /// </summary>
        public static string BackupManagerNewBackupWindowTitle {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse in explorer....
        /// </summary>
        public static string BackupManagerWindowBrowseInExplorer {
            get {
                return ResourceManager.GetString("BackupManagerWindowBrowseInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically create backups each week.
        /// </summary>
        public static string BackupManagerWindowCreateAutomaticBackups {
            get {
                return ResourceManager.GetString("BackupManagerWindowCreateAutomaticBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create backups.
        /// </summary>
        public static string BackupManagerWindowCreateBackups {
            get {
                return ResourceManager.GetString("BackupManagerWindowCreateBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup at \&quot;{0}\&quot; could not be restored..
        /// </summary>
        public static string BackupManagerWindowErrorRestore {
            get {
                return ResourceManager.GetString("BackupManagerWindowErrorRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From directory....
        /// </summary>
        public static string BackupManagerWindowFromDirectory {
            get {
                return ResourceManager.GetString("BackupManagerWindowFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From deterministic wallet seed....
        /// </summary>
        public static string BackupManagerWindowFromSeed {
            get {
                return ResourceManager.GetString("BackupManagerWindowFromSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From selection.
        /// </summary>
        public static string BackupManagerWindowFromSelection {
            get {
                return ResourceManager.GetString("BackupManagerWindowFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup has been successfully restored and applied..
        /// </summary>
        public static string BackupManagerWindowInformationRestoreSuccessful {
            get {
                return ResourceManager.GetString("BackupManagerWindowInformationRestoreSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backups.
        /// </summary>
        public static string BackupManagerWindowRestoreBackups {
            get {
                return ResourceManager.GetString("BackupManagerWindowRestoreBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup manager.
        /// </summary>
        public static string BackupManagerWindowTitle {
            get {
                return ResourceManager.GetString("BackupManagerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be EXTREMELY CAREFUL about storing your wallet data!
        ///
        ///No one else should be able to access them, as this would cause your money to be compromised..
        /// </summary>
        public static string BackupManagerWindowWarningNewBackup {
            get {
                return ResourceManager.GetString("BackupManagerWindowWarningNewBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove recipient.
        /// </summary>
        public static string CoinSenderRemoveRecipient {
            get {
                return ResourceManager.GetString("CoinSenderRemoveRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon.
        /// </summary>
        public static string DebugWindowConsoleDaemon {
            get {
                return ResourceManager.GetString("DebugWindowConsoleDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consoles.
        /// </summary>
        public static string DebugWindowConsoles {
            get {
                return ResourceManager.GetString("DebugWindowConsoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug window.
        /// </summary>
        public static string DebugWindowTitle {
            get {
                return ResourceManager.GetString("DebugWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MainWindowOverview {
            get {
                return ResourceManager.GetString("MainWindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send coins.
        /// </summary>
        public static string MainWindowSendCoins {
            get {
                return ResourceManager.GetString("MainWindowSendCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string MainWindowTransactions {
            get {
                return ResourceManager.GetString("MainWindowTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Monero Client.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Backup manager.
        /// </summary>
        public static string MenuBackupManager {
            get {
                return ResourceManager.GetString("MenuBackupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change wallet passphrase....
        /// </summary>
        public static string MenuChangeWalletPassphrase {
            get {
                return ResourceManager.GetString("MenuChangeWalletPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Debug window.
        /// </summary>
        public static string MenuDebugWindow {
            get {
                return ResourceManager.GetString("MenuDebugWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Encrypt wallet....
        /// </summary>
        public static string MenuEncryptWallet {
            get {
                return ResourceManager.GetString("MenuEncryptWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export....
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window.
        /// </summary>
        public static string MenuHideWindow {
            get {
                return ResourceManager.GetString("MenuHideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string MenuShowWindow {
            get {
                return ResourceManager.GetString("MenuShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unlock wallet....
        /// </summary>
        public static string MenuUnlockWallet {
            get {
                return ResourceManager.GetString("MenuUnlockWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string OptionsAppearance {
            get {
                return ResourceManager.GetString("OptionsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface language:.
        /// </summary>
        public static string OptionsAppearanceLanguage {
            get {
                return ResourceManager.GetString("OptionsAppearanceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string OptionsAppearanceLanguageNameDefault {
            get {
                return ResourceManager.GetString("OptionsAppearanceLanguageNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneral {
            get {
                return ResourceManager.GetString("OptionsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save databases before shutdown.
        /// </summary>
        public static string OptionsGeneralIsSafeShutdownEnabled {
            get {
                return ResourceManager.GetString("OptionsGeneralIsSafeShutdownEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Monero Client on system login.
        /// </summary>
        public static string OptionsGeneralIsStartableOnSystemLogin {
            get {
                return ResourceManager.GetString("OptionsGeneralIsStartableOnSystemLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string OptionsPaths {
            get {
                return ResourceManager.GetString("OptionsPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet backups:.
        /// </summary>
        public static string OptionsPathsDirectoryWalletBackups {
            get {
                return ResourceManager.GetString("OptionsPathsDirectoryWalletBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet data:.
        /// </summary>
        public static string OptionsPathsFileWalletData {
            get {
                return ResourceManager.GetString("OptionsPathsFileWalletData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon software:.
        /// </summary>
        public static string OptionsPathsSoftwareDaemon {
            get {
                return ResourceManager.GetString("OptionsPathsSoftwareDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner software:.
        /// </summary>
        public static string OptionsPathsSoftwareMiner {
            get {
                return ResourceManager.GetString("OptionsPathsSoftwareMiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet software:.
        /// </summary>
        public static string OptionsPathsSoftwareWallet {
            get {
                return ResourceManager.GetString("OptionsPathsSoftwareWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string OverviewInitializing {
            get {
                return ResourceManager.GetString("OverviewInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of transactions:.
        /// </summary>
        public static string OverviewNumberOfTransactions {
            get {
                return ResourceManager.GetString("OverviewNumberOfTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent transactions.
        /// </summary>
        public static string OverviewRecentTransactions {
            get {
                return ResourceManager.GetString("OverviewRecentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendable:.
        /// </summary>
        public static string OverviewSpendable {
            get {
                return ResourceManager.GetString("OverviewSpendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed:.
        /// </summary>
        public static string OverviewUnconfirmed {
            get {
                return ResourceManager.GetString("OverviewUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting URI is too long.
        ///
        ///Please try to reduce the length of your inputs!.
        /// </summary>
        public static string QrCodeWindowUriTooLong {
            get {
                return ResourceManager.GetString("QrCodeWindowUriTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipient.
        /// </summary>
        public static string SendCoinsAddRecipient {
            get {
                return ResourceManager.GetString("SendCoinsAddRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string SendCoinsBalance {
            get {
                return ResourceManager.GetString("SendCoinsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recipients.
        /// </summary>
        public static string SendCoinsClearRecipients {
            get {
                return ResourceManager.GetString("SendCoinsClearRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix count:.
        /// </summary>
        public static string SendCoinsMixCount {
            get {
                return ResourceManager.GetString("SendCoinsMixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction could not be sent..
        /// </summary>
        public static string SendCoinsTransactionCouldNotBeSent {
            get {
                return ResourceManager.GetString("SendCoinsTransactionCouldNotBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections.
        /// </summary>
        public static string StatusBarConnections {
            get {
                return ResourceManager.GetString("StatusBarConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with network....
        /// </summary>
        public static string StatusBarStatusSynchronizing {
            get {
                return ResourceManager.GetString("StatusBarStatusSynchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string StatusBarSyncTextDayPlural {
            get {
                return ResourceManager.GetString("StatusBarSyncTextDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string StatusBarSyncTextDaySingular {
            get {
                return ResourceManager.GetString("StatusBarSyncTextDaySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string StatusBarSyncTextHourPlural {
            get {
                return ResourceManager.GetString("StatusBarSyncTextHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string StatusBarSyncTextHourSingular {
            get {
                return ResourceManager.GetString("StatusBarSyncTextHourSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blocks ({1}) behind.
        /// </summary>
        public static string StatusBarSyncTextMain {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string StatusBarSyncTextMinutePlural {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string StatusBarSyncTextMinuteSingular {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not interrupt this process!.
        /// </summary>
        public static string TaskbarDoNotInterruptProcess {
            get {
                return ResourceManager.GetString("TaskbarDoNotInterruptProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monero Client is shutting down....
        /// </summary>
        public static string TaskbarShutdown {
            get {
                return ResourceManager.GetString("TaskbarShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming transaction.
        /// </summary>
        public static string TaskbarTransactionIncoming {
            get {
                return ResourceManager.GetString("TaskbarTransactionIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing transaction.
        /// </summary>
        public static string TaskbarTransactionOutgoing {
            get {
                return ResourceManager.GetString("TaskbarTransactionOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type transaction.
        /// </summary>
        public static string TaskbarTransactionUnknownType {
            get {
                return ResourceManager.GetString("TaskbarTransactionUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TextAddress {
            get {
                return ResourceManager.GetString("TextAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        public static string TextAddressBook {
            get {
                return ResourceManager.GetString("TextAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TextAmount {
            get {
                return ResourceManager.GetString("TextAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string TextClear {
            get {
                return ResourceManager.GetString("TextClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monero Client.
        /// </summary>
        public static string TextClientName {
            get {
                return ResourceManager.GetString("TextClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMR.
        /// </summary>
        public static string TextCurrencyCode {
            get {
                return ResourceManager.GetString("TextCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string TextExport {
            get {
                return ResourceManager.GetString("TextExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.
        /// </summary>
        public static string TextFilterAllFiles {
            get {
                return ResourceManager.GetString("TextFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated file (*.csv)|*.csv.
        /// </summary>
        public static string TextFilterCsvFiles {
            get {
                return ResourceManager.GetString("TextFilterCsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables (*.exe)|*.exe.
        /// </summary>
        public static string TextFilterExecutableFiles {
            get {
                return ResourceManager.GetString("TextFilterExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG files (*.png)|*.png.
        /// </summary>
        public static string TextFilterPngFiles {
            get {
                return ResourceManager.GetString("TextFilterPngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet files (*.bin)|*.bin.
        /// </summary>
        public static string TextFilterWalletFiles {
            get {
                return ResourceManager.GetString("TextFilterWalletFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Monero address.
        /// </summary>
        public static string TextHintAddress {
            get {
                return ResourceManager.GetString("TextHintAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a label for this address to add it to your address book.
        /// </summary>
        public static string TextHintLabel {
            get {
                return ResourceManager.GetString("TextHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is optional.
        /// </summary>
        public static string TextHintOptional {
            get {
                return ResourceManager.GetString("TextHintOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TextInformation {
            get {
                return ResourceManager.GetString("TextInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string TextLabel {
            get {
                return ResourceManager.GetString("TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string TextMessage {
            get {
                return ResourceManager.GetString("TextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string TextNew {
            get {
                return ResourceManager.GetString("TextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TextOk {
            get {
                return ResourceManager.GetString("TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string TextPaste {
            get {
                return ResourceManager.GetString("TextPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment ID:.
        /// </summary>
        public static string TextPaymentId {
            get {
                return ResourceManager.GetString("TextPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        public static string TextQrCode {
            get {
                return ResourceManager.GetString("TextQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string TextSaveAs {
            get {
                return ResourceManager.GetString("TextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TextSend {
            get {
                return ResourceManager.GetString("TextSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string TextWallet {
            get {
                return ResourceManager.GetString("TextWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TextWarning {
            get {
                return ResourceManager.GetString("TextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendable?.
        /// </summary>
        public static string TransactionsSpendable {
            get {
                return ResourceManager.GetString("TransactionsSpendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string TransactionsTransactionId {
            get {
                return ResourceManager.GetString("TransactionsTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TransactionsType {
            get {
                return ResourceManager.GetString("TransactionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string TransactionTypeReceive {
            get {
                return ResourceManager.GetString("TransactionTypeReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TransactionTypeSend {
            get {
                return ResourceManager.GetString("TransactionTypeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string TransactionTypeUnknown {
            get {
                return ResourceManager.GetString("TransactionTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to again.
        /// </summary>
        public static string WalletChangePassphraseWindowAgain {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current passphrase:.
        /// </summary>
        public static string WalletChangePassphraseWindowCurrentPassphrase {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowCurrentPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a passphrase for your wallet in order to keep it safe!.
        /// </summary>
        public static string WalletChangePassphraseWindowInstruction1 {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (It&apos;s recommended to use at least 10 random characters or 8 words.).
        /// </summary>
        public static string WalletChangePassphraseWindowInstruction2 {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passphrase.
        /// </summary>
        public static string WalletChangePassphraseWindowNewPassphrase {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowNewPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string WalletChangePassphraseWindowPassphrase {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied passphrases do not match..
        /// </summary>
        public static string WalletChangePassphraseWindowPassphrasesDoNotMatch {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowPassphrasesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change wallet passphrase.
        /// </summary>
        public static string WalletChangePassphraseWindowTitleChangePassphrase {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowTitleChangePassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt wallet.
        /// </summary>
        public static string WalletChangePassphraseWindowTitleEncryptWallet {
            get {
                return ResourceManager.GetString("WalletChangePassphraseWindowTitleEncryptWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your passphrase in order to access your wallet..
        /// </summary>
        public static string WalletUnlockWindowInstruction {
            get {
                return ResourceManager.GetString("WalletUnlockWindowInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock wallet.
        /// </summary>
        public static string WalletUnlockWindowTitle {
            get {
                return ResourceManager.GetString("WalletUnlockWindowTitle", resourceCulture);
            }
        }
    }
}
