//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jojatekok.MoneroGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jojatekok.MoneroGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons made by:.
        /// </summary>
        internal static string AboutWindowCreditIcons {
            get {
                return ResourceManager.GetString("AboutWindowCreditIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading license file....
        /// </summary>
        internal static string AboutWindowLicenseFileLoading {
            get {
                return ResourceManager.GetString("AboutWindowLicenseFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The license file cannot be found..
        /// </summary>
        internal static string AboutWindowLicenseFileNotFound {
            get {
                return ResourceManager.GetString("AboutWindowLicenseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party licenses.
        /// </summary>
        internal static string AboutWindowThirdPartyLicenses {
            get {
                return ResourceManager.GetString("AboutWindowThirdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MoneroX.
        /// </summary>
        internal static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to again.
        /// </summary>
        internal static string AccountChangePassphraseWindowAgain {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current passphrase:.
        /// </summary>
        internal static string AccountChangePassphraseWindowCurrentPassphrase {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowCurrentPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a passphrase for your account in order to keep it safe!.
        /// </summary>
        internal static string AccountChangePassphraseWindowInstruction1 {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (It&apos;s recommended to use at least 10 random characters or 8 words.).
        /// </summary>
        internal static string AccountChangePassphraseWindowInstruction2 {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passphrase.
        /// </summary>
        internal static string AccountChangePassphraseWindowNewPassphrase {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowNewPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        internal static string AccountChangePassphraseWindowPassphrase {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied passphrases do not match..
        /// </summary>
        internal static string AccountChangePassphraseWindowPassphrasesDoNotMatch {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowPassphrasesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account passphrase.
        /// </summary>
        internal static string AccountChangePassphraseWindowTitleChangePassphrase {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowTitleChangePassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt account.
        /// </summary>
        internal static string AccountChangePassphraseWindowTitleEncryptAccount {
            get {
                return ResourceManager.GetString("AccountChangePassphraseWindowTitleEncryptAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your passphrase in order to access your account..
        /// </summary>
        internal static string AccountUnlockWindowInstruction {
            get {
                return ResourceManager.GetString("AccountUnlockWindowInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock account.
        /// </summary>
        internal static string AccountUnlockWindowTitle {
            get {
                return ResourceManager.GetString("AccountUnlockWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address.
        /// </summary>
        internal static string AddressBookCopyAddress {
            get {
                return ResourceManager.GetString("AddressBookCopyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add known address.
        /// </summary>
        internal static string AddressBookEditWindowTitleAdd {
            get {
                return ResourceManager.GetString("AddressBookEditWindowTitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contact.
        /// </summary>
        internal static string AddressBookEditWindowTitleEdit {
            get {
                return ResourceManager.GetString("AddressBookEditWindowTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account&apos;s deterministic seed can be found below. It&apos;s recommended to make note of it on a paper instead of storing it on an electronic device..
        /// </summary>
        internal static string BackupManagerDeterministicAccountSeedWindowInstruction {
            get {
                return ResourceManager.GetString("BackupManagerDeterministicAccountSeedWindowInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve the deterministic seed of the account being used..
        /// </summary>
        internal static string BackupManagerNewBackupWindowErrorRetrievingSeed {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowErrorRetrievingSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a method for creating the new backup!.
        /// </summary>
        internal static string BackupManagerNewBackupWindowInstructionMain {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowInstructionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a file, at a chosen path.
        /// </summary>
        internal static string BackupManagerNewBackupWindowSelectionAsFileCustom1 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsFileCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These files will not appear as selectable in the built-in backup manager.
        /// </summary>
        internal static string BackupManagerNewBackupWindowSelectionAsFileCustom2 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsFileCustom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a file, at the default location.
        /// </summary>
        internal static string BackupManagerNewBackupWindowSelectionAsFileDefault {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsFileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a deterministic account seed.
        /// </summary>
        internal static string BackupManagerNewBackupWindowSelectionAsSeed1 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsSeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is the safest, and it doesn&apos;t even require a computer for storage.
        /// </summary>
        internal static string BackupManagerNewBackupWindowSelectionAsSeed2 {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowSelectionAsSeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New backup.
        /// </summary>
        internal static string BackupManagerNewBackupWindowTitle {
            get {
                return ResourceManager.GetString("BackupManagerNewBackupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse in explorer....
        /// </summary>
        internal static string BackupManagerWindowBrowseInExplorer {
            get {
                return ResourceManager.GetString("BackupManagerWindowBrowseInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically create backups each week.
        /// </summary>
        internal static string BackupManagerWindowCreateAutomaticBackups {
            get {
                return ResourceManager.GetString("BackupManagerWindowCreateAutomaticBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create backups.
        /// </summary>
        internal static string BackupManagerWindowCreateBackups {
            get {
                return ResourceManager.GetString("BackupManagerWindowCreateBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup at \&quot;{0}\&quot; could not be restored..
        /// </summary>
        internal static string BackupManagerWindowErrorRestore {
            get {
                return ResourceManager.GetString("BackupManagerWindowErrorRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From directory....
        /// </summary>
        internal static string BackupManagerWindowFromDirectory {
            get {
                return ResourceManager.GetString("BackupManagerWindowFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From deterministic account seed....
        /// </summary>
        internal static string BackupManagerWindowFromSeed {
            get {
                return ResourceManager.GetString("BackupManagerWindowFromSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From selection.
        /// </summary>
        internal static string BackupManagerWindowFromSelection {
            get {
                return ResourceManager.GetString("BackupManagerWindowFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup has been successfully restored and applied..
        /// </summary>
        internal static string BackupManagerWindowInformationRestoreSuccessful {
            get {
                return ResourceManager.GetString("BackupManagerWindowInformationRestoreSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backups.
        /// </summary>
        internal static string BackupManagerWindowRestoreBackups {
            get {
                return ResourceManager.GetString("BackupManagerWindowRestoreBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup manager.
        /// </summary>
        internal static string BackupManagerWindowTitle {
            get {
                return ResourceManager.GetString("BackupManagerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be EXTREMELY CAREFUL about storing your account data!
        ///
        ///No one else should be able to access them, as this would cause your money to be compromised..
        /// </summary>
        internal static string BackupManagerWindowWarningNewBackup {
            get {
                return ResourceManager.GetString("BackupManagerWindowWarningNewBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove recipient.
        /// </summary>
        internal static string CoinSenderRemoveRecipient {
            get {
                return ResourceManager.GetString("CoinSenderRemoveRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consoles.
        /// </summary>
        internal static string DebugWindowConsoles {
            get {
                return ResourceManager.GetString("DebugWindowConsoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug window.
        /// </summary>
        internal static string DebugWindowTitle {
            get {
                return ResourceManager.GetString("DebugWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string MainWindowOverview {
            get {
                return ResourceManager.GetString("MainWindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send coins.
        /// </summary>
        internal static string MainWindowSendCoins {
            get {
                return ResourceManager.GetString("MainWindowSendCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string MainWindowTransactions {
            get {
                return ResourceManager.GetString("MainWindowTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates..
        /// </summary>
        internal static string MainWindowUpdateError {
            get {
                return ResourceManager.GetString("MainWindowUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available (v{0}). Do you want to apply it now?.
        /// </summary>
        internal static string MainWindowUpdateQuestionMessage {
            get {
                return ResourceManager.GetString("MainWindowUpdateQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string MainWindowUpdateQuestionTitle {
            get {
                return ResourceManager.GetString("MainWindowUpdateQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is currently not the default for opening &apos;{0}&apos; URIs. Would you like to make it the default?.
        /// </summary>
        internal static string MainWindowUriAssociationQuestionMessage {
            get {
                return ResourceManager.GetString("MainWindowUriAssociationQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default URI association.
        /// </summary>
        internal static string MainWindowUriAssociationQuestionTitle {
            get {
                return ResourceManager.GetString("MainWindowUriAssociationQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been received to send a payment with the following details:.
        /// </summary>
        internal static string MainWindowUriOpenQuestionMessage1 {
            get {
                return ResourceManager.GetString("MainWindowUriOpenQuestionMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to navigate to the &apos;{0}&apos; tab?.
        /// </summary>
        internal static string MainWindowUriOpenQuestionMessage2 {
            get {
                return ResourceManager.GetString("MainWindowUriOpenQuestionMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open this URI?.
        /// </summary>
        internal static string MainWindowUriOpenQuestionTitle {
            get {
                return ResourceManager.GetString("MainWindowUriOpenQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About MoneroX.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup manager.
        /// </summary>
        internal static string MenuBackupManager {
            get {
                return ResourceManager.GetString("MenuBackupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Change account passphrase....
        /// </summary>
        internal static string MenuChangeAccountPassphrase {
            get {
                return ResourceManager.GetString("MenuChangeAccountPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug window.
        /// </summary>
        internal static string MenuDebugWindow {
            get {
                return ResourceManager.GetString("MenuDebugWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Encrypt account....
        /// </summary>
        internal static string MenuEncryptAccount {
            get {
                return ResourceManager.GetString("MenuEncryptAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export....
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window.
        /// </summary>
        internal static string MenuHideWindow {
            get {
                return ResourceManager.GetString("MenuHideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        internal static string MenuShowWindow {
            get {
                return ResourceManager.GetString("MenuShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unlock account....
        /// </summary>
        internal static string MenuUnlockAccount {
            get {
                return ResourceManager.GetString("MenuUnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string OptionsAppearance {
            get {
                return ResourceManager.GetString("OptionsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface language:.
        /// </summary>
        internal static string OptionsAppearanceLanguage {
            get {
                return ResourceManager.GetString("OptionsAppearanceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string OptionsAppearanceLanguageNameDefault {
            get {
                return ResourceManager.GetString("OptionsAppearanceLanguageNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string OptionsGeneral {
            get {
                return ResourceManager.GetString("OptionsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save databases before shutdown.
        /// </summary>
        internal static string OptionsGeneralIsSafeShutdownEnabled {
            get {
                return ResourceManager.GetString("OptionsGeneralIsSafeShutdownEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start MoneroX on system login.
        /// </summary>
        internal static string OptionsGeneralIsStartableOnSystemLogin {
            get {
                return ResourceManager.GetString("OptionsGeneralIsStartableOnSystemLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string OptionsGeneralIsUpdateCheckEnabled {
            get {
                return ResourceManager.GetString("OptionsGeneralIsUpdateCheckEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow checking for experimental builds.
        /// </summary>
        internal static string OptionsGeneralIsUpdateCheckForTestBuildsEnabled {
            get {
                return ResourceManager.GetString("OptionsGeneralIsUpdateCheckForTestBuildsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always check whether the application is the default handler of the currency&apos;s URIs.
        /// </summary>
        internal static string OptionsGeneralIsUriAssociationCheckEnabled {
            get {
                return ResourceManager.GetString("OptionsGeneralIsUriAssociationCheckEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string OptionsNetwork {
            get {
                return ResourceManager.GetString("OptionsNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the corresponding process locally.
        /// </summary>
        internal static string OptionsNetworkIsProcessHostedLocally {
            get {
                return ResourceManager.GetString("OptionsNetworkIsProcessHostedLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect through proxy.
        /// </summary>
        internal static string OptionsNetworkIsProxyEnabled {
            get {
                return ResourceManager.GetString("OptionsNetworkIsProxyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string OptionsNetworkProxySettings {
            get {
                return ResourceManager.GetString("OptionsNetworkProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC server.
        /// </summary>
        internal static string OptionsNetworkRpcServerSettings {
            get {
                return ResourceManager.GetString("OptionsNetworkRpcServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string OptionsPaths {
            get {
                return ResourceManager.GetString("OptionsPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account backups:.
        /// </summary>
        internal static string OptionsPathsDirectoryAccountBackups {
            get {
                return ResourceManager.GetString("OptionsPathsDirectoryAccountBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon data:.
        /// </summary>
        internal static string OptionsPathsDirectoryDaemonData {
            get {
                return ResourceManager.GetString("OptionsPathsDirectoryDaemonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account data:.
        /// </summary>
        internal static string OptionsPathsFileAccountData {
            get {
                return ResourceManager.GetString("OptionsPathsFileAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account software:.
        /// </summary>
        internal static string OptionsPathsSoftwareAccountManager {
            get {
                return ResourceManager.GetString("OptionsPathsSoftwareAccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon software:.
        /// </summary>
        internal static string OptionsPathsSoftwareDaemon {
            get {
                return ResourceManager.GetString("OptionsPathsSoftwareDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string OverviewInitializing {
            get {
                return ResourceManager.GetString("OverviewInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of transactions:.
        /// </summary>
        internal static string OverviewNumberOfTransactions {
            get {
                return ResourceManager.GetString("OverviewNumberOfTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent transactions.
        /// </summary>
        internal static string OverviewRecentTransactions {
            get {
                return ResourceManager.GetString("OverviewRecentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendable:.
        /// </summary>
        internal static string OverviewSpendable {
            get {
                return ResourceManager.GetString("OverviewSpendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed:.
        /// </summary>
        internal static string OverviewUnconfirmed {
            get {
                return ResourceManager.GetString("OverviewUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string PunctuationColon {
            get {
                return ResourceManager.GetString("PunctuationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string PunctuationQuestionMark {
            get {
                return ResourceManager.GetString("PunctuationQuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to enlarge!.
        /// </summary>
        internal static string QrCodeWindowImageEnlarge {
            get {
                return ResourceManager.GetString("QrCodeWindowImageEnlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to shrink!.
        /// </summary>
        internal static string QrCodeWindowImageShrink {
            get {
                return ResourceManager.GetString("QrCodeWindowImageShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an address!.
        /// </summary>
        internal static string QrCodeWindowUriNoAddress {
            get {
                return ResourceManager.GetString("QrCodeWindowUriNoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting URI is too long.
        ///
        ///Please try to reduce the length of your inputs!.
        /// </summary>
        internal static string QrCodeWindowUriTooLong {
            get {
                return ResourceManager.GetString("QrCodeWindowUriTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipient.
        /// </summary>
        internal static string SendCoinsAddRecipient {
            get {
                return ResourceManager.GetString("SendCoinsAddRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recipients.
        /// </summary>
        internal static string SendCoinsClearRecipients {
            get {
                return ResourceManager.GetString("SendCoinsClearRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance:.
        /// </summary>
        internal static string SendCoinsCurrentBalance {
            get {
                return ResourceManager.GetString("SendCoinsCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated new balance:.
        /// </summary>
        internal static string SendCoinsEstimatedNewBalance {
            get {
                return ResourceManager.GetString("SendCoinsEstimatedNewBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the recipients&apos; addresses belongs to an exchange. Do you want to cancel sending the transaction without a payment ID?.
        /// </summary>
        internal static string SendCoinsExchangeSendWithoutPaymentIdQuestionMessage {
            get {
                return ResourceManager.GetString("SendCoinsExchangeSendWithoutPaymentIdQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment ID missing.
        /// </summary>
        internal static string SendCoinsExchangeSendWithoutPaymentIdQuestionTitle {
            get {
                return ResourceManager.GetString("SendCoinsExchangeSendWithoutPaymentIdQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee:.
        /// </summary>
        internal static string SendCoinsFee {
            get {
                return ResourceManager.GetString("SendCoinsFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment ID you&apos;ve specified is not valid..
        /// </summary>
        internal static string SendCoinsInvalidPaymentId {
            get {
                return ResourceManager.GetString("SendCoinsInvalidPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix count:.
        /// </summary>
        internal static string SendCoinsMixCount {
            get {
                return ResourceManager.GetString("SendCoinsMixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction could not be sent..
        /// </summary>
        internal static string SendCoinsTransactionCouldNotBeSent {
            get {
                return ResourceManager.GetString("SendCoinsTransactionCouldNotBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections.
        /// </summary>
        internal static string StatusBarConnections {
            get {
                return ResourceManager.GetString("StatusBarConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with network....
        /// </summary>
        internal static string StatusBarStatusSynchronizing {
            get {
                return ResourceManager.GetString("StatusBarStatusSynchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1} blocks of transaction history ({2}% done).
        ///The last received block was generated {3} ago..
        /// </summary>
        internal static string StatusBarStatusTextMain {
            get {
                return ResourceManager.GetString("StatusBarStatusTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        internal static string StatusBarStatusUpToDate {
            get {
                return ResourceManager.GetString("StatusBarStatusUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string StatusBarSyncTextDayPlural {
            get {
                return ResourceManager.GetString("StatusBarSyncTextDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string StatusBarSyncTextDaySingular {
            get {
                return ResourceManager.GetString("StatusBarSyncTextDaySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string StatusBarSyncTextHourPlural {
            get {
                return ResourceManager.GetString("StatusBarSyncTextHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string StatusBarSyncTextHourSingular {
            get {
                return ResourceManager.GetString("StatusBarSyncTextHourSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blocks ({1}) behind.
        /// </summary>
        internal static string StatusBarSyncTextMain {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string StatusBarSyncTextMinutePlural {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string StatusBarSyncTextMinuteSingular {
            get {
                return ResourceManager.GetString("StatusBarSyncTextMinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not interrupt this process!.
        /// </summary>
        internal static string TaskbarDoNotInterruptProcess {
            get {
                return ResourceManager.GetString("TaskbarDoNotInterruptProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneroX is shutting down....
        /// </summary>
        internal static string TaskbarShutdown {
            get {
                return ResourceManager.GetString("TaskbarShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming transaction.
        /// </summary>
        internal static string TaskbarTransactionIncoming {
            get {
                return ResourceManager.GetString("TaskbarTransactionIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing transaction.
        /// </summary>
        internal static string TaskbarTransactionOutgoing {
            get {
                return ResourceManager.GetString("TaskbarTransactionOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type transaction.
        /// </summary>
        internal static string TaskbarTransactionUnknownType {
            get {
                return ResourceManager.GetString("TaskbarTransactionUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string TextAccount {
            get {
                return ResourceManager.GetString("TextAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account manager.
        /// </summary>
        internal static string TextAccountManager {
            get {
                return ResourceManager.GetString("TextAccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string TextAddress {
            get {
                return ResourceManager.GetString("TextAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        internal static string TextAddressBook {
            get {
                return ResourceManager.GetString("TextAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TextAmount {
            get {
                return ResourceManager.GetString("TextAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string TextClear {
            get {
                return ResourceManager.GetString("TextClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneroX.
        /// </summary>
        internal static string TextClientName {
            get {
                return ResourceManager.GetString("TextClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMR.
        /// </summary>
        internal static string TextCurrencyCode {
            get {
                return ResourceManager.GetString("TextCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon.
        /// </summary>
        internal static string TextDaemon {
            get {
                return ResourceManager.GetString("TextDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deterministic account seed.
        /// </summary>
        internal static string TextDeterministicAccountSeed {
            get {
                return ResourceManager.GetString("TextDeterministicAccountSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again.
        /// </summary>
        internal static string TextDoNotAskAgain {
            get {
                return ResourceManager.GetString("TextDoNotAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        internal static string TextExport {
            get {
                return ResourceManager.GetString("TextExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account files (*.bin)|*.bin.
        /// </summary>
        internal static string TextFilterAccountFiles {
            get {
                return ResourceManager.GetString("TextFilterAccountFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.
        /// </summary>
        internal static string TextFilterAllFiles {
            get {
                return ResourceManager.GetString("TextFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated file (*.csv)|*.csv.
        /// </summary>
        internal static string TextFilterCsvFiles {
            get {
                return ResourceManager.GetString("TextFilterCsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables (*.exe)|*.exe.
        /// </summary>
        internal static string TextFilterExecutableFiles {
            get {
                return ResourceManager.GetString("TextFilterExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG files (*.png)|*.png.
        /// </summary>
        internal static string TextFilterPngFiles {
            get {
                return ResourceManager.GetString("TextFilterPngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Monero address.
        /// </summary>
        internal static string TextHintAddress {
            get {
                return ResourceManager.GetString("TextHintAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a label for this address to add it to your address book.
        /// </summary>
        internal static string TextHintLabel {
            get {
                return ResourceManager.GetString("TextHintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is optional.
        /// </summary>
        internal static string TextHintOptional {
            get {
                return ResourceManager.GetString("TextHintOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        internal static string TextHost {
            get {
                return ResourceManager.GetString("TextHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TextInformation {
            get {
                return ResourceManager.GetString("TextInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string TextLabel {
            get {
                return ResourceManager.GetString("TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string TextMessage {
            get {
                return ResourceManager.GetString("TextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string TextNew {
            get {
                return ResourceManager.GetString("TextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TextOk {
            get {
                return ResourceManager.GetString("TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string TextPaste {
            get {
                return ResourceManager.GetString("TextPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment ID:.
        /// </summary>
        internal static string TextPaymentId {
            get {
                return ResourceManager.GetString("TextPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string TextPort {
            get {
                return ResourceManager.GetString("TextPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        internal static string TextQrCode {
            get {
                return ResourceManager.GetString("TextQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string TextSaveAs {
            get {
                return ResourceManager.GetString("TextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string TextSend {
            get {
                return ResourceManager.GetString("TextSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TextWarning {
            get {
                return ResourceManager.GetString("TextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendable?.
        /// </summary>
        internal static string TransactionsSpendable {
            get {
                return ResourceManager.GetString("TransactionsSpendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        internal static string TransactionsTransactionId {
            get {
                return ResourceManager.GetString("TransactionsTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TransactionsType {
            get {
                return ResourceManager.GetString("TransactionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string TransactionTypeReceive {
            get {
                return ResourceManager.GetString("TransactionTypeReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string TransactionTypeSend {
            get {
                return ResourceManager.GetString("TransactionTypeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string TransactionTypeUnknown {
            get {
                return ResourceManager.GetString("TransactionTypeUnknown", resourceCulture);
            }
        }
    }
}
